// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPxxjt8zprR7a7e--f-18qkOhdLcsYtJk',
    appId: '1:295551567405:web:18adf5e79f2edbe77c5aa4',
    messagingSenderId: '295551567405',
    projectId: 'flutter-blog-app-e2c14',
    authDomain: 'flutter-blog-app-e2c14.firebaseapp.com',
    storageBucket: 'flutter-blog-app-e2c14.appspot.com',
    measurementId: 'G-XFBJ3VN26C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6x1cw35tiKRfaWSgsPiwRz8-JOlgt1FE',
    appId: '1:295551567405:android:6364f01e8a7c9bd87c5aa4',
    messagingSenderId: '295551567405',
    projectId: 'flutter-blog-app-e2c14',
    storageBucket: 'flutter-blog-app-e2c14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvKo_2jN8nmeZOUr_YPwz6YOzoTmvXRCY',
    appId: '1:295551567405:ios:ed040bc78ea215b47c5aa4',
    messagingSenderId: '295551567405',
    projectId: 'flutter-blog-app-e2c14',
    storageBucket: 'flutter-blog-app-e2c14.appspot.com',
    iosBundleId: 'com.example.flutterBlogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvKo_2jN8nmeZOUr_YPwz6YOzoTmvXRCY',
    appId: '1:295551567405:ios:2878520557da67777c5aa4',
    messagingSenderId: '295551567405',
    projectId: 'flutter-blog-app-e2c14',
    storageBucket: 'flutter-blog-app-e2c14.appspot.com',
    iosBundleId: 'com.example.flutterBlogApp.RunnerTests',
  );
}
